name: 💡 Feature request
description: Suggest a new capability or small improvement.
title: "[FEAT] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Quick idea? Drop it here—we just need the essentials.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line description of your idea.
      placeholder: Remember the last selected menu date
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: Why it matters
      description: Who benefits and what pain does it solve?
      placeholder: Admins recreate the same date every morning; saving it would speed up prep.
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested approach (optional)
      description: Optional details, mockups, or alternate ideas.
      placeholder: Maybe store the last menu date server-side and prefill the admin form.
