"""initial

Revision ID: bdfcdaebcab1
Revises:
Create Date: 2025-09-22 13:19:12.591411

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "bdfcdaebcab1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_sort_order"), "categories", ["sort_order"], unique=False)
    op.create_index(op.f("ix_categories_title"), "categories", ["title"], unique=True)
    op.create_table(
        "daily_menus",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_daily_menus_created_at"), "daily_menus", ["created_at"], unique=False)
    op.create_table(
        "images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("file_data", sa.LargeBinary(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_images_created_at"), "images", ["created_at"], unique=False)
    op.create_index(op.f("ix_images_filename"), "images", ["filename"], unique=True)
    op.create_table(
        "menu_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_menu_settings_key"), "menu_settings", ["key"], unique=True)
    op.create_table(
        "units",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_units_name"), "units", ["name"], unique=True)
    op.create_index(op.f("ix_units_sort_order"), "units", ["sort_order"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("unit_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["image_id"], ["images.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_items_category_id"), "items", ["category_id"], unique=False)
    op.create_index(op.f("ix_items_image_id"), "items", ["image_id"], unique=False)
    op.create_index(op.f("ix_items_name"), "items", ["name"], unique=False)
    op.create_index(op.f("ix_items_unit_id"), "items", ["unit_id"], unique=False)
    op.create_table(
        "daily_menu_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("daily_menu_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["daily_menu_id"], ["daily_menus.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("daily_menu_id", "item_id", name="uq_daily_menu_items_daily_menu_item"),
    )
    op.create_index(op.f("ix_daily_menu_items_daily_menu_id"), "daily_menu_items", ["daily_menu_id"], unique=False)
    op.create_index(op.f("ix_daily_menu_items_item_id"), "daily_menu_items", ["item_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_daily_menu_items_item_id"), table_name="daily_menu_items")
    op.drop_index(op.f("ix_daily_menu_items_daily_menu_id"), table_name="daily_menu_items")
    op.drop_table("daily_menu_items")
    op.drop_index(op.f("ix_items_unit_id"), table_name="items")
    op.drop_index(op.f("ix_items_name"), table_name="items")
    op.drop_index(op.f("ix_items_image_id"), table_name="items")
    op.drop_index(op.f("ix_items_category_id"), table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_units_sort_order"), table_name="units")
    op.drop_index(op.f("ix_units_name"), table_name="units")
    op.drop_table("units")
    op.drop_index(op.f("ix_menu_settings_key"), table_name="menu_settings")
    op.drop_table("menu_settings")
    op.drop_index(op.f("ix_images_filename"), table_name="images")
    op.drop_index(op.f("ix_images_created_at"), table_name="images")
    op.drop_table("images")
    op.drop_index(op.f("ix_daily_menus_created_at"), table_name="daily_menus")
    op.drop_table("daily_menus")
    op.drop_index(op.f("ix_categories_title"), table_name="categories")
    op.drop_index(op.f("ix_categories_sort_order"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
